### ISSUE TITLE
♻️  Migrate to non-nullable by default

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_candies#5]
In order to keep up with the coming null safety, we've scheduled to migrate all necessary packages (projects are not included since they generally required further packages to migrate) into nnbd (non-nullable by default). Packages are listed below.

Be aware that some packages might not migrated forever, since the codeowner is no longer working with Flutter. 🙏 

Sorted by code owner:

### @zmtzawqlp
- [x] [extended_image](https://github.com/fluttercandies/extended_image)
  - [x] [extended_image_library](https://github.com/fluttercandies/extended_image_library)
- [x] [extended_text](https://github.com/fluttercandies/extended_text)
- [x] [extended_text_field](https://github.com/fluttercandies/extended_text_field)
  - [x] [extended_text_library](https://github.com/fluttercandies/extended_text_library)
- [x] [extended_list](https://github.com/fluttercandies/extended_list)
  - [x] [extended_list_library](https://github.com/fluttercandies/extended_list_library)
- [x] [extended_nested_scroll_view](https://github.com/fluttercandies/extended_nested_scroll_view)
- [x] [extended_tabs](https://github.com/fluttercandies/extended_tabs)
- [x] [extended_sliver](https://github.com/fluttercandies/extended_sliver)
- [x] [ff_annotation_route](https://github.com/fluttercandies/ff_annotation_route)
  - [x] [ff_annotation_route_core](https://github.com/fluttercandies/ff_annotation_route_core)
  - [x] [ff_annotation_route_library](https://github.com/fluttercandies/ff_annotation_route_library)
  - to use null-safety/non-null-safety: https://github.com/fluttercandies/flutter_candies/issues/5#issuecomment-790431760
- [x] [waterfall_flow](https://github.com/fluttercandies/waterfall_flow)
- [x] [pull_to_refresh_notification](https://github.com/fluttercandies/pull_to_refresh_notification)
- [x] [loading_more_list](https://github.com/fluttercandies/loading_more_list)
  - [x] [loading_more_list_library](https://github.com/fluttercandies/loading_more_list_library)
- [x] [like_button](https://github.com/fluttercandies/like_button)
- [x] [http_client_helper](https://github.com/fluttercandies/http_client_helper)
- [x] [JsonToDart](https://github.com/fluttercandies/JsonToDart)
- [ ] [assets_generator](https://github.com/fluttercandies/assets_generator)

### @AlexV525
- [x] [flutter_wechat_assets_picker](https://github.com/fluttercandies/flutter_wechat_assets_picker)
- [x] [flutter_wechat_camera_picker](https://github.com/fluttercandies/flutter_wechat_camera_picker)
- [ ] [flutter_custom_inspector](https://github.com/fluttercandies/flutter_custom_inspector)
- [x] [ripple_backdrop_animate_route](https://github.com/fluttercandies/ripple_backdrop_animate_route)

### @CaiJingLong
- [x] [flutter_image_editor](https://github.com/fluttercandies/flutter_image_editor)
- [ ] [simple_provider](https://github.com/fluttercandies/simple_provider)
- [x] [adaptation](https://github.com/fluttercandies/adaptation)
- [x] [properties](https://github.com/fluttercandies/properties)

### @CNAD666
- [x] [flutter_smart_dialog](https://github.com/fluttercandies/flutter_smart_dialog)

### @gzlock
- [x] [flutter_draggable_container](https://github.com/fluttercandies/flutter_draggable_container)

### @wanglu1209
- [x] [w_popup_menu](https://github.com/fluttercandies/w_popup_menu)

### @mjl0602
- [x] [fconsole](https://github.com/fluttercandies/fconsole)
- [x] [left-scroll-actions](https://github.com/fluttercandies/left-scroll-actions)

### @shingohu
- [x] [flutter_filereader](https://github.com/fluttercandies/flutter_filereader)
- [x] [flutter_record_mp3](https://github.com/fluttercandies/flutter_record_mp3)

### @LXD312569496
- [ ] [flutter_custom_calendar](https://github.com/fluttercandies/flutter_custom_calendar)

### @ysdy44 @nohli
- [x] [flutter_hsvcolor_picker](https://github.com/fluttercandies/flutter_hsvcolor_picker)

### @ahyangnb
- [ ] [blue_flutter](https://github.com/fluttercandies/blue_flutter)
- [ ] [nav_router](https://github.com/fluttercandies/nav_router)

**Comment by CaiJingLong** [comment]
flutter_image_editor migration completed

**Comment by CaiJingLong** [comment]
[adaptation](https://github.com/fluttercandies/adaptation) done.

**Comment by gzlock** [comment]
将会重写 flutter_draggable_container 实现 https://github.com/fluttercandies/flutter_draggable_container/issues/3 的需求

**Comment by zmtzawqlp** [comment]
## ff_annotation_route
`pub global activate ff_annotation_route`

*  non-null-safety
  
`pub global activate ff_annotation_route 6.x.x-non-null-safety`


*  null-safety

``` yaml
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ff_annotation_route_core: ^2.0.0
  ff_annotation_route_library: ^2.0.0
``` 

*  non-null-safety
  
``` yaml
environment:
  sdk: '>=2.6.0 <2.12.0'
dependencies:
  ff_annotation_route_core: ^2.0.1-non-null-safety
  ff_annotation_route_library: ^2.0.1-non-null-safety
```

**Comment by CNAD666** [comment]
**flutter_smart_dialog already migrate null-safety**

`Version distinction`

- null-safety

```dart
dependencies:
  flutter_smart_dialog: ^2.0.0
```

- non-null-safety（last stable version）

```dart
dependencies:
  flutter_smart_dialog: ^1.3.1
```

**Comment by gzlock** [comment]
flutter_draggable_container 改造完成，已经支持null safety.

**Comment by wanglu1209** [comment]
w_popup_menu already migrate null-safety

Version distinction

null-safety
dependencies:   w_popup_menu: ^1.0.0

non-null-safety（last stable version）
dependencies:   flutter_smart_dialog: ^0.3.1





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttercandies/flutter_candies"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年2月26日(星期五) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[fluttercandies/flutter_candies] ♻️  Migrate to non-nullable by default (#5)





 
In order to keep up with the coming null safety, we're scheduling to migrate all necessary packages (projects are not included since they generally required further packages to migrate) into nnbd (non-nullable by default). Packages are listed below:
 
Sorted by code owner:
 
@zmtzawqlp
  
 extended_image  
 extended_image_library
  
 
 extended_text  
 extended_text_field
 
 extended_text_library
  
 
 extended_list  
 extended_list_library
  
 
 extended_nested_scroll_view
 
 extended_tabs
 
 ff_annotation_route  
 ff_annotation_route_core
 
 ff_annotation_route_library
  
 
 waterfall_flow
 
 pull_to_refresh_notification
 
 loading_more_list  
 loading_more_list_library
  
 
 like_button
 
 http_client_helper
  
@AlexV525
  
 flutter_wechat_assets_picker
 
 flutter_wechat_camera_picker
 
 flutter_custom_inspector
 
 ripple_backdrop_animate_route
  
@CaiJingLong
  
 flutter_image_editor
 
 simple_provider
 
 adaptation
 
 properties
  
@mjl0602
  
 fconsole
 
 left-scroll-actions
  
@shingohu
  
 flutter_filereader
 
 flutter_record_mp3
  
@wanglu1209
  
 w_popup_menu
  
@LXD312569496
  
 flutter_custom_calendar
  
@ysdy44
  
 flutter_hsvcolor_picker
  
@CNAD666
  
 flutter_smart_dialog
  
@ahyangnb
  
 blue_flutter
 
 nav_router
  
@gzlock
  
 flutter_draggable_container

**Comment by wanglu1209** [comment]
w_popup_menu already migrate null-safety

Version distinction

null-safety
dependencies:   w_popup_menu: ^1.0.0

non-null-safety（last stable version）
dependencies:   w_popup_menu: ^0.3.1





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "fluttercandies/flutter_candies"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年2月26日(星期五) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[fluttercandies/flutter_candies] ♻️  Migrate to non-nullable by default (#5)





 
In order to keep up with the coming null safety, we're scheduling to migrate all necessary packages (projects are not included since they generally required further packages to migrate) into nnbd (non-nullable by default). Packages are listed below:
 
Sorted by code owner:
 
@zmtzawqlp
  
 extended_image  
 extended_image_library
  
 
 extended_text  
 extended_text_field
 
 extended_text_library
  
 
 extended_list  
 extended_list_library
  
 
 extended_nested_scroll_view
 
 extended_tabs
 
 ff_annotation_route  
 ff_annotation_route_core
 
 ff_annotation_route_library
  
 
 waterfall_flow
 
 pull_to_refresh_notification
 
 loading_more_list  
 loading_more_list_library
  
 
 like_button
 
 http_client_helper
  
@AlexV525
  
 flutter_wechat_assets_picker
 
 flutter_wechat_camera_picker
 
 flutter_custom_inspector
 
 ripple_backdrop_animate_route
  
@CaiJingLong
  
 flutter_image_editor
 
 simple_provider
 
 adaptation
 
 properties
  
@mjl0602
  
 fconsole
 
 left-scroll-actions
  
@shingohu
  
 flutter_filereader
 
 flutter_record_mp3
  
@wanglu1209
  
 w_popup_menu
  
@LXD312569496
  
 flutter_custom_calendar
  
@ysdy44
  
 flutter_hsvcolor_picker
  
@CNAD666
  
 flutter_smart_dialog
  
@ahyangnb
  
 blue_flutter
 
 nav_router
  
@gzlock
  
 flutter_draggable_container
